//
// Copyright (c) 2008 Tridium, Inc.
// Licensed under the Academic Free License version 3.0
//
// History:
//   16 Oct 08  Brian Frank  Creation
//
package sedonac.jasm;
                   
import java.io.*;                   
import sedona.util.*;
import sedonac.*;
import sedonac.Compiler;
import sedonac.namespace.*;

/**          
 * JavaClass stores a Java classfile generated by JavaKitAsm
 */
public class JavaClass  
{                       

////////////////////////////////////////////////////////////////
// Methods
////////////////////////////////////////////////////////////////

  public String path() 
  { 
    return JavaClassAsm.jname(kitName, name) + ".class"; 
  }

  public String toString() 
  { 
    return qname; 
  }

////////////////////////////////////////////////////////////////
// Fields
////////////////////////////////////////////////////////////////
                                    
  public String kitName;      // kit name
  public String name;         // simple type name
  public String qname;        // qualified Sedona name acme::Foo
  public Buffer classfile;    // Java bytecode classfile
}

